### ISSUE TITLE
About how dcp unpack when it face a unpack issue

### ISSUE THREAD

**Issue by woodliu** [exdx/dcp#116]
Hi, i come across a issus with `Error: failed to unpack` when i unpack a image to local folder. And i understand why this happened by [FAQ](https://github.com/exdx/dcp?tab=readme-ov-file#faq). 
But i have a question about how it works. Does it unpack all the image files expect the ones like symlinks, or just stop unpacking when it fail to unpack a file? Thanks!

**Comment by exdx** [comment]
Hey @woodliu 

Looking at the `tar` documentation it looks like symlinked files are just skipped https://docs.rs/tar/latest/src/tar/archive.rs.html#95-97
I would recommend confirming locally as well

**Comment by woodliu** [comment]
> Hey @woodliu
> 
> Looking at the `tar` documentation it looks like symlinked files are just skipped https://docs.rs/tar/latest/src/tar/archive.rs.html#95-97 I would recommend confirming locally as well

Thanks @exdx , it seems it unpacks all the files, thank you!
