### ISSUE TITLE
add support for podman

### ISSUE THREAD

**Issue by grokspawn** [exdx/dcp#26]
https://github.com/vv9k/podman-api-rs is a rust i/f to podman

By same author, perhaps the single lib https://github.com/vv9k/containers-api would allow access to both?

**Comment by exdx** [comment]
I'm inclined to believe this is important, especially since we produce a linux binary, enough users would be interested. I don't run podman locally, but we can probably setup CI to test it.

**Comment by exdx** [comment]
I think a good implementation would abstract over docker/podman types and provide a generic interface for container manipulation. The runtime type can be an enum called `Runtime` and have docker and podman as variants. 

I would like to avoid the scenario of having two separate identical codepaths, so generics are really key for this feature.

**Comment by exdx** [comment]
@grokspawn I put up a PR #33 which adds support for podman. Please review if you get a chance.
