### ISSUE TITLE
feature: create directory as part of unpacking

### ISSUE THREAD

**Issue by exdx** [exdx/dcp#28]
As a user, I would like dcp to be able to create a directory (a subdirectory of the current working directory, for example) when unpacking contents, so I don't need to create the directory manually before hand. 

One option is to introduce a new flag, `-o`, that when set creates a directory on the local filesystem. 

Another option is to use the existing `-d` flag to create a directory if one does not exist already.

**Comment by tylerslaton** [comment]
> Another option is to use the existing -d flag to create a directory if one does not exist already.

I believe right now if you use the `--content-path` option right now, it will create the directory for you if it doesn't already exist based on the path you provided. That being said, I agree that having this default to something that create the directory inside of relative path would make sense. Perhaps something like `./output` would be a logical default and you can specify `--content-path` to change that.
