### ISSUE TITLE
copy files into docker 

### ISSUE THREAD

**Issue by jinfagang** [exdx/dcp#49]
copy files into docker

**Comment by exdx** [comment]
Hi @jinfagang, thanks for opening an issue about this 👍 . I've thought about this before too, but I'm not entirely sure whether to implement it. 

- I see containers as immutable deployment artifacts, which should not be manually modified at runtime. For example, the container digest specifies a specific version of the image contents, and modifying it would negate the value of using a digest. So copying files inside the container at runtime feels like a bit of anti-pattern. 
- dcp is somewhat limited in what it can do -- most k8s distributions use either containerd or crio as the container runtime, and dcp cannot interface with those. So it wouldn't be able to copy data into a live container running on k8s for example, or extract data out. 

That being said, if you have a specific use-case in mind, we can discuss further and potentially look at implementing something like this.

**Comment by jinfagang** [comment]
hi, you are right, seems docker are imutable.

**Comment by exdx** [comment]
Closing for now.
