### ISSUE TITLE
Support sha256 image tags

### ISSUE THREAD

**Issue by timflannagan** [exdx/dcp#60]
I tried running dcp on an OLM registry+v1 bundle image but that failed with the following error:

```bash
$ dcp --content-path output registry.redhat.io/openshift-update-service/cincinnati-operator-bundle@sha256:3feccb95e912f2d710958e701a1b52acf16a676fde9a8219491ad9381e6284ea
error 400 Bad Request - invalid reference format
"d8f1b22b1239673912ad2555e16e3e790c994d9d87f599f044c808160b246b56"
Error: Error(Fault { code: 404, message: "Could not find the file output in container d8f1b22b1239673912ad2555e16e3e790c994d9d87f599f044c808160b246b56" })
```

And that image is pullable via docker:

```bash
$ docker pull registry.redhat.io/openshift-update-service/cincinnati-operator-bundle@sha256:3feccb95e912f2d710958e701a1b52acf16a676fde9a8219491ad9381e6284ea
registry.redhat.io/openshift-update-service/cincinnati-operator-bundle@sha256:3feccb95e912f2d710958e701a1b52acf16a676fde9a8219491ad9381e6284ea: Pulling from openshift-update-service/cincinnati-operator-bundle
d83fa9b96fa1: Pull complete 
Digest: sha256:3feccb95e912f2d710958e701a1b52acf16a676fde9a8219491ad9381e6284ea
Status: Downloaded newer image for registry.redhat.io/openshift-update-service/cincinnati-operator-bundle@sha256:3feccb95e912f2d710958e701a1b52acf16a676fde9a8219491ad9381e6284ea
```

**Comment by exdx** [comment]
Hi @timflannagan -- did you use the latest version of dcp? This was recently fixed in #56 and the fix is only present in the v0.3.2+ release.

**Comment by timflannagan** [comment]
Nope, that dcp executable was probably built closer to shift week. I'll rebuild and try again in a bit.

**Comment by exdx** [comment]
Also are you sure the content path is `output`? Should it be `manifests` instead?

**Comment by exdx** [comment]
The download-path may be `output`, is what you're referencing here

**Comment by timflannagan** [comment]
Yeah, I had read the `--help` output for those flags and got confused with their usage. I ended up re-tagging the sha256 tag, and using dcp with the --download-path flag and it worked.

**Comment by exdx** [comment]
Nice. Glad it worked. I will close this issue for now.
